[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'
via_ir = true
use_literal_content = true
etherscan_api_key = '${ETHERSCAN_API_KEY}'

[rpc_endpoints]
goerli = '${GOERLI_RPC_URL}'

[etherscan]
goerli = { key = '${ETHERSCAN_API_KEY}' }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
